#Thi Thực Hành Đại Số Tuyến Tính

In [18]:
#Võ Ngọc Duy - 2474802010071
#Câu 1
import numpy as np
import math
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
#a/
tong_AB = A + B
tich_so = 2*A + 3*B
print("a/")
print("A + B =", tong_AB)
print("2A + 3B =", tich_so)
# b/
tich_vo_huong = np.dot(A, B)
do_dai_A = np.linalg.norm(A)
do_dai_B = np.linalg.norm(B)
cos_goc = tich_vo_huong/ (do_dai_A * do_dai_B)
goc_do = math.degrees(math.acos(cos_goc))
print("\nb/")
print("A.B =", tich_vo_huong)
print("góc giữa A và B =", round(goc_do, 3), "độ")
#c/
C_CT = np.dot(C, C.T)
print("\nc/")
print("C*C^T =")
print(C_CT)


a/
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

b/
A.B = -5
góc giữa A và B = 99.594 độ

c/
C*C^T =
[[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [19]:
#Câu 2
import numpy as np
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])

N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]])

#a/
MN = np.dot(M, N)
print("a/")
print("M× N=")
print(MN)
#b/
det_M = np.linalg.det(M)
print("\nb/")
print("định thức của M =", round(det_M, 3))
#c/
rank_N = np.linalg.matrix_rank(N)
print("\nc/")
print("hạng của N =", rank_N)


a/
M× N=
[[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b/
định thức của M = 409.0

c/
hạng của N = 4


In [20]:
#Câu 3
import numpy as np
P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])
b = np.array([6, 8, 3, 7])
#a/
det_P = np.linalg.det(P)
print("a/")
if det_P == 0:
    print("ma trận P không khả nghịch vì định thức bằng 0.")
else:
    P_inv = np.linalg.inv(P)
    print("ma trận nghịch đảo của P là:")
    print(P_inv)
#b/
x = np.dot(P_inv, b)
print("\nb/")
print("nghiệm của hệ phương trình (x, y, z, w) là:")
print(x)
#c/
kiemtra = np.dot(P, x)
print("\nc/")
print("P × nghiệm =", kiemtra)
print("so sánh với vector hằng số b =", b)


a/
ma trận nghịch đảo của P là:
[[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]

b/
nghiệm của hệ phương trình (x, y, z, w) là:
[2.         1.71428571 0.42857143 0.85714286]

c/
P × nghiệm = [6. 8. 3. 7.]
so sánh với vector hằng số b = [6 8 3 7]


In [21]:
#Câu 4
import numpy as np
Q = np.array([[5, -2, 1],
              [0, 3, -1],
              [2, 0, 4]])
#a/
gia_tri_rieng, vector_rieng = np.linalg.eig(Q)
print("a/")
print("các giá trị riêng của Q là:")
print(np.round(gia_tri_rieng, 3))
#b/
print("\nb/")
print("các vector riêng tương ứng:")
print(np.round(vector_rieng, 3))
#c/
vector_chuan_hoa = vector_rieng/ np.linalg.norm(vector_rieng, axis=0)
print("\nc/")
print("các vector riêng sau khi chuẩn hóa:")
print(np.round(vector_chuan_hoa, 3))


a/
các giá trị riêng của Q là:
[6.355+0.j    2.822+1.077j 2.822-1.077j]

b/
các vector riêng tương ứng:
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]

c/
các vector riêng sau khi chuẩn hóa:
[[ 0.748+0.j    -0.374+0.342j -0.374-0.342j]
 [-0.189+0.j     0.095+0.574j  0.095-0.574j]
 [ 0.636+0.j     0.636+0.j     0.636-0.j   ]]


In [22]:
#Câu 5
import numpy as np
R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])
b = np.array([12, 5, 9])
#a/
x = np.linalg.solve(R, b)
print("a/")
print("nghiệm của hệ phương trình x =")
print(np.round(x, 3))
#b/
dinh_thuc = np.linalg.det(R)
print("\nb/")
if dinh_thuc == 0:
    print("ma trận R không khả nghịch (định thức = 0).")
else:
    R_nghich_dao = np.linalg.inv(R)
    x2 = np.dot(R_nghich_dao, b)
    print("ma trận R khả nghịch, nghịch đảo của R là:")
    print(np.round(R_nghich_dao, 3))
    print("giải hệ bằng R⁻¹ × b, nghiệm x' =")
    print(np.round(x2, 3))
    print("so sánh với nghiệm ở câu a:", np.allclose(x, x2))
#c/
chuan_F = np.linalg.norm(R, 'fro')
print("\nc/")
print("chuẩn Frobenius của R =", round(chuan_F, 3))


a/
nghiệm của hệ phương trình x =
[2.788 1.529 1.188]

b/
ma trận R khả nghịch, nghịch đảo của R là:
[[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]
giải hệ bằng R⁻¹ × b, nghiệm x' =
[2.788 1.529 1.188]
so sánh với nghiệm ở câu a: True

c/
chuẩn Frobenius của R = 8.0
