#BÀI TẬP CHƯƠNG 2

In [2]:
#Võ Ngọc Duy - 2474802010071
#thực hành 1

v = [3, 5, 7]
w = [2, 4, 6]
#hàm scalescale
def scale(c, v):
    return [c * vi for vi in v]
print("scale(10, v):", scale(10, v))
#hàm cộng hai vector
def sumvector(v, w):
    return [vi + wi for vi, wi in zip(v, w)]
print("sumvector(v, w):", sumvector(v, w))
#hàm nhân 2 vector vô hướng
def dotvector(v, w):
    return sum(vi * wi for vi, wi in zip(v, w))
print("dot(v, w):", dotvector(v, w))
#hàm tính chiều dài
def lenvector(v):
    return dotvector(v, v)
print("lenvector(v):", lenvector(v))

scale(10, v): [30, 50, 70]
sumvector(v, w): [5, 9, 13]
dot(v, w): 68
lenvector(v): 83


In [5]:
#thực hành 2

import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
phanloai2 = np.select(
    [scores >= 0, scores < 0],
    ["so duong", "so am"],
    default = "khong xac dinh"
)
print("Phân loại 2 loại:", phanloai2)
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])

phanloai3 = np.select(
    [scores > 0, scores == 0, scores < 0],
    ["so duong", "so 0", "so am"],
    default = "khong xac dinh"
)
print("Phân loại 3 loại:", phanloai3)


Phân loại 2 loại: ['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']
Phân loại 3 loại: ['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


In [9]:
#thực hành 2
import numpy as np
from scipy import linalg, sparse
from sympy import symbols, solve

D = np.asmatrix([[3, 4], [5, 6]])
print("Ma trận D:\n", D, "\n")

C = np.asmatrix(np.random.random((5, 7)))
print("Ma trận C:\n", C, "\n")

A = np.asmatrix(np.random.random((2, 2)))
print("Ma trận A:\n", A, "\n")

b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)
print("Mảng b:\n", b, "\n")
print("Ma trận B (asmatrix):\n", B, "\n")

print("Ma trận chuyển vị A.T:\n", A.T, "\n")
print("Ma trận nghịch đảo A.I:\n", A.I, "\n")
print("Ma trận nghịch đảo bằng scipy:\n", linalg.inv(A), "\n")

M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])
M_lower = np.tril(M)
print("Ma trận tam giác dưới:\n", M_lower, "\n")

M_upper = np.triu(M)
print("Ma trận tam giác trên:\n", M_upper, "\n")

v_diag = np.diag(M)
print("Vector đường chéo:\n", v_diag, "\n")

M_diag = np.diag(v_diag)
print("Ma trận từ vector đường chéo:\n", M_diag, "\n")

I2 = np.identity(2)
print("Ma trận đơn vị I2:\n", I2, "\n")

x, y, z = symbols('x y z')
eq1 = x**2 + 2 - 6
eq2 = y - 1 - 6
eq3 = x + z - 1
eq4 = 2 * x - 8
eq5 = z**2 + 4 - (y - z)

result = solve([eq1, eq2, eq3, eq4, eq5], (x, y, z))
print("Nghiệm tìm được (x, y, z):", result, "\n")

x_list = [1, 2, 3]
y_list = [1, 2, 3]
print("So sánh danh sách x == y:", all([x_list[i] == y_list[i] for i in range(len(x_list))]), "\n")

y_list2 = [1, 2, 4]
print("So sánh danh sách x == y2:", all([x_list[i] == y_list2[i] for i in range(len(x_list))]), "\n")

a1 = np.array([1, 2])
a2 = np.array([1, 2])
print("So sánh mảng a1 == a2:", np.array_equal(a1, a2), "\n")

print("So sánh mảng trực tiếp:", np.array_equal(np.array([1, 2]), np.array([1, 2])), "\n")

print("np.array_equiv(A, B): kiểm tra xem hai mảng có tương đương không (shape có thể khác)\n")
print("np.allclose(A, B): kiểm tra xem hai mảng có gần bằng nhau không (với sai số nhỏ)\n")


Ma trận D:
 [[3 4]
 [5 6]] 

Ma trận C:
 [[0.0369688  0.94793784 0.12077711 0.8350452  0.77383677 0.17385346
  0.12635712]
 [0.23449857 0.58508621 0.78851698 0.76277609 0.91499824 0.11281452
  0.76620194]
 [0.54038216 0.06205558 0.33476458 0.90373361 0.25250904 0.53399234
  0.69522853]
 [0.66289964 0.25716307 0.88922286 0.78000692 0.0394585  0.37707001
  0.30946713]
 [0.62192317 0.43316529 0.17386958 0.18986979 0.24152194 0.95334818
  0.00577419]] 

Ma trận A:
 [[0.02954114 0.08910602]
 [0.86272279 0.76148019]] 

Mảng b:
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]] 

Ma trận B (asmatrix):
 [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]] 

Ma trận chuyển vị A.T:
 [[0.02954114 0.86272279]
 [0.08910602 0.76148019]] 

Ma trận nghịch đảo A.I:
 [[-14.00325399   1.63861678]
 [ 15.86505664  -0.54324727]] 

Ma trận nghịch đảo bằng scipy:
 [[-14.00325399   1.63861678]
 [ 15.86505664  -0.54324727]] 

Ma trận tam giác dưới:
 [[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]] 

Ma trận tam giác trên:
 [[-1

In [8]:
#thực hành 3,2

import numpy as np
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

I6 = np.identity(6)
print("\nMa trận đơn vị I6:")
print(I6)

print("\nSố phần tử trong A:")
print(A.size)

print("\nĐường chéo chính của A:")
print(np.matrix.diagonal(A))

A = A + I6
print("\nMa trận A sau khi cộng với ma trận đơn vị I6:")
print(A)

vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("\nTích A nhân với vecB:")
print(C)

D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D:")
print(D)


E = A.dot(D.T)
print("\nTích A x D.T:")
print(E)

F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0.], [5., 1.], [6., 0.]])
print("\nMa trận F:")
print(F)

G = A.dot(F)
print("\nTích A x F:")
print(G)

#tính ma trận nghịch đảo của A
A_inv = np.linalg.inv(A)
print("\nMa trận nghịch đảo của A:")
print(A_inv)

#tính ma trận nghịch đảo của ma trận nghịch đảo của A
A_inv_inv = np.linalg.inv(np.linalg.inv(A))
print("\nKết quả của np.linalg.inv(np.linalg.inv(A)):")
print(A_inv_inv)

print("\nSo sánh A với nghịch đảo của nghịch đảo A (gần đúng):")
print(np.allclose(A, A_inv_inv))


Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận đơn vị I6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Số phần tử trong A:
36

Đường chéo chính của A:
[ 0.  7. 14. 21. 28. 35.]

Ma trận A sau khi cộng với ma trận đơn vị I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]

Tích A nhân với vecB:
[ 71. 198. 325. 452. 579. 706.]

Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

Tích A x D.T:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

Tích A x F:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận nghịch đảo của A:
[[ 0

In [10]:
#thực hành 4
import numpy as np
A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10
print("các số Fibonacci đầu tiên:")
print(f"F0 = {b[1]}")
print(f"F1 = {b[0]}")

#tính các số Fibonacci
for i in range(n):
    b = A.dot(b)
    print(f"F{i+2} = {b[0]}")


các số Fibonacci đầu tiên:
F0 = 0
F1 = 1
F2 = 1
F3 = 2
F4 = 3
F5 = 5
F6 = 8
F7 = 13
F8 = 21
F9 = 34
F10 = 55
F11 = 89


In [12]:
# Bài toán 5.2 - Đếm xe vào khu vực trung tâm
from sympy import symbols, solve
import numpy as np
x1, x2, x3, x4 = symbols('x1 x2 x3 x4')
#hệ phương trình
pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520
#sympy
nghiem = solve((pt1, pt2, pt3, pt4), (x1, x2, x3, x4))
print("Kết quả bằng sympy:")
print(nghiem)
#ma trận
A = np.array([
    [-1,  0,  0,  1],
    [ 1, -1,  0,  0],
    [ 0,  1, -1,  0],
    [ 0,  0,  1, -1]
], dtype=float)
B = np.array([-160, 240, -600, 520], dtype=float)
#dùng lstsq
X, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)
print("\nkết quả bằng numpy (lstsq):")
for i, xi in enumerate(X, 1):
    print(f"x{i} = {xi}")
#nghịch đảo của ma trận
try:
    A_inv = np.linalg.inv(A)
    print("\nma trận nghịch đảo của A:")
    print(A_inv)
except np.linalg.LinAlgError:
    print("\nma trận A không có ma trận nghịch đảo")


Kết quả bằng sympy:
{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

kết quả bằng numpy (lstsq):
x1 = 10.000000000000078
x2 = -230.00000000000006
x3 = 370.0
x4 = -150.0

ma trận A không có ma trận nghịch đảo


#BÀI TẬP VỀ NHÀ

In [13]:
#bài tập 1
import numpy as np
#vấn đề 1
A1 = np.array([[1, -1], [2, 3]])
B1 = np.array([-2, 6])
x1 = np.linalg.solve(A1, B1)
print("vấn đề 1:", x1)
#vấn đề 2
A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
B2 = np.array([2, 3, 6])
x2 = np.linalg.solve(A2, B2)
print("vấn đề 2:", x2)
#vấn đề 3
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
B3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, B3)
print("vấn đề 3: a, b, c =", x3)
#vấn đề 4
A4 = np.array([[1, 0, 1], [1, -2, -3], [-2, 2, 0]])
B4 = np.array([1, -3, 0])
x4 = np.linalg.solve(A4, B4)
print("vấn đề 4: a, b, c =", x4)


vấn đề 1: [0. 2.]
vấn đề 2: [3. 1. 2.]
vấn đề 3: a, b, c = [ 1. -4.  7.]
vấn đề 4: a, b, c = [-0. -0.  1.]


In [14]:
#bài tập 2
from sympy import symbols, Eq, solve, Matrix
x, y, z, a, b, c = symbols('x y z a b c')
#vấn đề 1
eqs1 = [Eq(x - y, -2), Eq(2*x + 3*y, 6)]
sol1 = solve(eqs1, (x, y))
print("vấn đề 1:", sol1)
#vấn đề 2
eqs2 = [Eq(x - y, 2), Eq(2*x - y - z, 3), Eq(x + y + z, 6)]
sol2 = solve(eqs2, (x, y, z))
print("vấn đề 2:", sol2)
#vấn đề 3
eqs3 = [Eq(a + b + c, 4), Eq(4*a + 2*b + c, 3), Eq(9*a + 3*b + c, 4)]
sol3 = solve(eqs3, (a, b, c))
print("vấn đề 3:", sol3)
#vấn đề 4
eqs4 = [Eq(a + c, 1), Eq(a + b - 2*c, -3), Eq(-2*a + 2*b + c, 0)]
sol4 = solve(eqs4, (a, b, c))
print("vấn đề 4:", sol4)

vấn đề 1: {x: 0, y: 2}
vấn đề 2: {x: 3, y: 1, z: 2}
vấn đề 3: {a: 1, b: -4, c: 7}
vấn đề 4: {a: -1/9, b: -2/3, c: 10/9}


In [17]:
#bài tập 3
import numpy as np
def luy_thua_ma_tran(F, k):
    ket_qua = np.identity(2, dtype=object)
    while k > 0:
        if k % 2 == 1:
            ket_qua = np.dot(ket_qua, F)
        F = np.dot(F, F)
        k //= 2
    return ket_qua

def ma_tran_Fibonacci(k):
    F = np.array([[1, 1], [1, 0]], dtype=object)
    Fk = luy_thua_ma_tran(F, k)
    print(f"Ma trận F^{k} là:")
    print(Fk)
    print("\nTheo lý thuyết, ta có:")
    print("F^k = [[Fib_{k+1}, Fib_k],")
    print("       [Fib_k,   Fib_{k-1}]]")

    print("\n=> Ma trận F^k chứa ba số Fibonacci liên tiếp:")
    print("   Fib_{k+1}, Fib_k, Fib_{k-1}")
#ví dụ key = 7
k = 7
matran_Fibonacci(k)




F^7 =
[[21 13]
 [13  8]]
Fib(8) = 21
Fib(7)   = 13
Fib(6) = 8
