#Bài Tập Chương 3

In [18]:
#Bài thực hành 1.1
# Võ Ngọc Duy - 2474802010071
from scipy import linalg
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1+0j, 2j, 3], (4, 5j, 6)])
c = np.array([[1, 0, 5], [0, 1, 2], [6.5, 4, 0], [7.8, 9.1, 1]])

A = np.asmatrix(np.random.random((2, 2)))
b = np.random.random((2, 2))
B = np.asmatrix(b)

C = np.asmatrix(np.random.random((10, 5)))
D = np.asmatrix([[4, 3], [2, 6]])
F = np.eye(3, k=1)

F1 = np.eye(3, k=0)  #đường chéo chính
print("F1 =\n", F1)
print()

F2 = np.eye(3, k=-1)  #đường chéo phụ
print("F2 =\n", F2)
print()

hang_C = np.linalg.matrix_rank(C)
print("Hạng của ma trận C =", hang_C)
print()

nghich_dao_A = A.I
print("Nghịch đảo của A (A.I):\n", nghich_dao_A)
print()

nghich_dao_A_scipy = linalg.inv(A)
print("Nghịch đảo của A (scipy):\n", nghich_dao_A_scipy)
print()

dinh_thuc_A = linalg.det(A)
print("Định thức của A =", dinh_thuc_A)
print()

chuyen_vi_A = A.T
print("Chuyển vị A:\n", chuyen_vi_A)
print()

chuyen_vi_lien_hop_A = A.H
print("Chuyển vị liên hợp của A:\n", chuyen_vi_lien_hop_A)
print()

b = np.array([1, 2])
nghiem = linalg.solve(A, b)
print("Nghiệm của hệ Ax = b là:", nghiem)
print()

F = np.eye(2, k=1)
E = np.asmatrix(A).T

x_lstsq, sai_so, hang, singular_values = linalg.lstsq(F, E)
print("Nghiệm gần đúng (least squares):\n", x_lstsq)
print()

print("A + D:\n", np.add(A, D))
print()

print("A - D:\n", np.subtract(A, D))
print()

print("A / D:\n", np.divide(A, D))
print()

print("A @ D:\n", A @ D)
print()

print("np.multiply(D, A):\n", np.multiply(D, A))
print()

print("np.dot(A, D):\n", np.dot(A, D))
print()

print("np.vdot(A, D):\n", np.vdot(A, D))
print()

exponential_A = linalg.expm(A)
print("Ma trận lũy thừa e^A:\n", exponential_A)
print()

logarit_A = linalg.logm(A)
print("Ma trận logarit log(A):\n", logarit_A)
print()


F1 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

F2 =
 [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Hạng của ma trận C = 5

Nghịch đảo của A (A.I):
 [[-1.01735796  1.21074775]
 [ 6.03896309 -0.02320525]]

Nghịch đảo của A (scipy):
 [[-1.01735796  1.21074775]
 [ 6.03896309 -0.02320525]]

Định thức của A = -0.1372108590064399

Chuyển vị A:
 [[0.00318401 0.82861131]
 [0.16612774 0.13959256]]

Chuyển vị liên hợp của A:
 [[0.00318401 0.82861131]
 [0.16612774 0.13959256]]

Nghiệm của hệ Ax = b là: [1.40413753 5.99255259]

Nghiệm gần đúng (least squares):
 [[0.         0.        ]
 [0.00318401 0.82861131]]

A + D:
 [[4.00318401 3.16612774]
 [2.82861131 6.13959256]]

A - D:
 [[-3.99681599 -2.83387226]
 [-1.17138869 -5.86040744]]

A / D:
 [[0.000796   0.05537591]
 [0.41430566 0.02326543]]

A @ D:
 [[0.34499153 1.00631847]
 [3.59363037 3.3233893 ]]

np.multiply(D, A):
 [[0.01273605 0.49838322]
 [1.65722263 0.83755536]]

np.dot(A, D):
 [[0.34499153 1.00631847]
 [3.59363037 3.3233893 ]]

np.vdot(A, D):
 [[0.0

In [19]:
#Bài thực hành 2,3
import numpy as np
#ma trận phân kỳ
#ma trận A
A = np.array([[0, 1], [1, 0]])
print("Ma trận A:")
print(A)
temp = A.dot(A)
print("\nA^2:")
print(temp)
k = 6
for i in range(k - 1):
    temp = temp.dot(A)
    print(f"\nA^{i+3}:")
    print(temp)
    print()

#ma trận B
B = np.array([[0, -1], [-1, 0]])
print("Ma trận B:")
print(B)
temp = B.dot(B)
print("\nB^2:")
print(temp)
k = 5
for i in range(k - 1):
    temp = temp.dot(B)
    print(f"\nB^{i+3}:")
    print(temp)
    print()

#ma trận hội tụ C
C = np.array([
    [1, 0, 0],
    [0.5, 1, 0],
    [0, 0.5, 1]
])
print("Ma trận C:")
print(C)
temp = C.dot(C)
print("\nC^2:")
print(temp)
k = 1000
for i in range(k - 1):
    temp = temp.dot(C)

print("\nC^1000:")
print(temp)
for i in range(k - 1):
    temp = temp.dot(C)
print("\nC^2000:")
print(temp)




Ma trận A:
[[0 1]
 [1 0]]

A^2:
[[1 0]
 [0 1]]

A^3:
[[0 1]
 [1 0]]


A^4:
[[1 0]
 [0 1]]


A^5:
[[0 1]
 [1 0]]


A^6:
[[1 0]
 [0 1]]


A^7:
[[0 1]
 [1 0]]

Ma trận B:
[[ 0 -1]
 [-1  0]]

B^2:
[[1 0]
 [0 1]]

B^3:
[[ 0 -1]
 [-1  0]]


B^4:
[[1 0]
 [0 1]]


B^5:
[[ 0 -1]
 [-1  0]]


B^6:
[[1 0]
 [0 1]]

Ma trận C:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.  0.5 1. ]]

C^2:
[[1.   0.   0.  ]
 [1.   1.   0.  ]
 [0.25 1.   1.  ]]

C^1000:
[[1.00000e+00 0.00000e+00 0.00000e+00]
 [5.00500e+02 1.00000e+00 0.00000e+00]
 [1.25125e+05 5.00500e+02 1.00000e+00]]

C^2000:
[[1.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e+03 1.0000e+00 0.0000e+00]
 [4.9975e+05 1.0000e+03 1.0000e+00]]


In [20]:
#Bài thực hành 2,4
import numpy as np
M = np.array([[0.8, 0.3],
              [0.2, 0.7]])
MM = M.dot(M)
print("M^2 =")
print(MM)
print()

MM = MM.dot(M)
print("M^3 =")
print(MM)
print()

for i in range(100):
    MM = MM.dot(M)
print("M^100 gần bằng M^oo =")
print(MM)


M^2 =
[[0.7  0.45]
 [0.3  0.55]]

M^3 =
[[0.65  0.525]
 [0.35  0.475]]

M^100 gần bằng M^oo =
[[0.6 0.6]
 [0.4 0.4]]


In [21]:
#Bài thực hành 3.2
import numpy as np
from scipy import linalg
M = np.array([
    [0.8, 0.3],
    [0.2, 0.7]
])
print("Ma trận M:")
print(M)
print()
P, L, U = linalg.lu(M)

print("ma trận P:")
print(P)
print()

print("ma trận L:")
print(L)
print()

print("ma trận U:")
print(U)
print()

print("L.dot(U):")
print(L.dot(U))
print()
print("nhận xét: kết quả của L.dot(U) (sau hoán vị nếu cần thiết với P) khớp với M")


Ma trận M:
[[0.8 0.3]
 [0.2 0.7]]

ma trận P:
[[1. 0.]
 [0. 1.]]

ma trận L:
[[1.   0.  ]
 [0.25 1.  ]]

ma trận U:
[[0.8   0.3  ]
 [0.    0.625]]

L.dot(U):
[[0.8 0.3]
 [0.2 0.7]]

nhận xét: kết quả của L.dot(U) (sau hoán vị nếu cần thiết với P) khớp với M


In [22]:
#Bài 5
import numpy as np
A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])
#tính A^2
A2 = A.dot(A)
print("A^2:")
print(A2)
#tính A^3
A3 = A2.dot(A)
print("\nA^3:")
print(A3)
#tổng A + A^2 + A^3
sumA = A + A2 + A3
print("\nA + A^2 + A^3:")
print(sumA)
k = 3
sumAk = A.copy()
temp = A.copy()

for i in range(1, k):
    temp = temp.dot(A)
    sumAk = sumAk + temp
print(f"\nTổng A + A^2 + ... + A^{k}:")
print(sumAk)


A^2:
[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]

A^3:
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]

A + A^2 + A^3:
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]

Tổng A + A^2 + ... + A^3:
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


#Bài Tập Về Nhà

In [25]:
#Bài 1
import numpy as np
#a/ tạo ma trận khả nghịch
A = np.array([[2, 1, 1],
              [1, 2, 1],
              [1, 1, 2]])
print("ma trận A:")
print(A)
if np.linalg.det(A) == 0:
    print("ma trận không khả nghịch")
    exit()
else:
    print("ma trận khả nghịch")

#b/ nhập chuỗi cần mã hóa
text = input("nhập tên hoặc mssv: ")

#c/ mã hóa chuỗi
data = [ord(c) for c in text]
while len(data) % 3 != 0:
    data.append(0)

blocks = np.array(data).reshape(-1, 3).T
encoded = A @ blocks
print("mã hóa:")
print(encoded)

#d/ giải mã
A_inv = np.linalg.inv(A)
decoded = np.round(A_inv @ encoded).astype(int)
flat = decoded.T.flatten()
result = ''.join(chr(x) for x in flat if x != 0)
print("giải mã:")
print(result)



ma trận A:
[[2 1 1]
 [1 2 1]
 [1 1 2]]
ma trận khả nghịch
nhập tên hoặc mssv: 2474802010071
mã hóa:
[[207 208 197 199  98]
 [209 212 195 199  49]
 [212 204 196 206  49]]
giải mã:
2474802010071


In [26]:
#Bài 2
#a
def compute_pq(c):
    M = [[1, 0], [0, 1]]

    for ci in c:
        Mi = [[ci, 1], [1, 0]]
        M = [
            [M[0][0]*Mi[0][0] + M[0][1]*Mi[1][0], M[0][0]*Mi[0][1] + M[0][1]*Mi[1][1]],
            [M[1][0]*Mi[0][0] + M[1][1]*Mi[1][0], M[1][0]*Mi[0][1] + M[1][1]*Mi[1][1]]
        ]
    p_n = M[0][0]
    q_n = M[1][0]
    return p_n, q_n

#b
def matrix_mult(A, B):
    return [
        [A[0][0]*B[0][0] + A[0][1]*B[1][0], A[0][0]*B[0][1] + A[0][1]*B[1][1]],
        [A[1][0]*B[0][0] + A[1][1]*B[1][0], A[1][0]*B[0][1] + A[1][1]*B[1][1]]
    ]
def compute_matrix_product(c):
    M = [[1, 0], [0, 1]]
    for ci in c:
        Mi = [[ci, 1], [1, 0]]
        M = matrix_mult(M, Mi)
    return M
def compute_vector_result(M):
    p_n = M[0][0]*1 + M[0][1]*0
    q_n = M[1][0]*1 + M[1][1]*0
    return p_n, q_n
