#Bài Tập Thực Hành

In [1]:
# Võ Ngọc Duy - 2474802010071
#Thực hành 1
import numpy as np
def sgn_by_def(sigma):
    inversions = 0
    for i in range(len(sigma) - 1):
        for j in range(i + 1, len(sigma)):
            if sigma[i] > sigma[j]:
                inversions += 1
    return (-1) ** inversions
sigma = np.array([2, 1, 3, 4])
print("\ndấu của hoán vị", sigma, "là:", sgn_by_def(sigma))

from itertools import permutations
n = 3
X = []
for i in range (1, n+1):
    X.append(i)
Sn = list(permutations(X))
print("\ntất cả các hoán vị của tập là: ")
print (Sn)

#Đoạn code 1:
def phatsinh_dinhthuc(n):
    x = list(range(1, n+1))
    Sn = list(permutations(x))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array(sn)
        product = ""
        for i in range(n):
            product += "a" + str(i+1) + str(sn[i])
        dau = sgn_by_def(sigma)
        if dau == 1:
            dinhthuc += " + " + product
        else:
            dinhthuc += " - " + product
    return dinhthuc
print("\nbiểu thức định thức cấp 2:")
print(phatsinh_dinhthuc(2))
print("\nbiểu thức định thức cấp 3:")
print(phatsinh_dinhthuc(3))

#Đoạn code 2:
def tinhtoan_dinhthuc(A):
    import math
    n = int(math.sqrt(A.size))
    x = list(range(1, n+1))
    Sn = list(permutations(x))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array(sn)
        product = 1
        for i in range(n):
            product *= A[i][sn[i] - 1]
        dau = sgn_by_def(sigma)
        if dau == 1:
            dinhthuc += product
        else:
            dinhthuc -= product
    return dinhthuc
matran = np.array([[3, 5, -8], [4, 12, -1], [2, 5, 3]])
print("\nma trận A:")
print(matran)
print("\ngiá trị định thức của A:")
print(tinhtoan_dinhthuc(matran))



dấu của hoán vị [2 1 3 4] là: -1

tất cả các hoán vị của tập là: 
[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]

biểu thức định thức cấp 2:
 + a11a22 - a12a21

biểu thức định thức cấp 3:
 + a11a22a33 - a11a23a32 - a12a21a33 + a12a23a31 + a13a21a32 - a13a22a31

ma trận A:
[[ 3  5 -8]
 [ 4 12 -1]
 [ 2  5  3]]

giá trị định thức của A:
85


In [2]:
#Thực hành 3
#Hệ hai phương trình tuyến tính bậc 1:
import numpy as np
from scipy import linalg
A = np.array([[4, -2], [3, -5]])
A1 = np.array([[10, -2], [11, -5]])
A2 = np.array([[4, 10], [3, 11]])
detA = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print("hệ 2 phương trình:")
print("detA =", detA, ", detA1 =", detA1, ", detA2 =", detA2)
if detA != 0:
    x1 = detA1 / detA
    x2 = detA2 / detA
    print("nghiệm của hệ là: x1 =", x1, ", x2 =", x2)
else:
    print("hệ phương trình vô nghiệm hoặc vô số nghiệm")

#Hệ ba phương trình tuyến tính bậc 1:
A = np.array([[-1, 2, -3], [2, -2, 1], [3, -4, 4]])
B = np.array([1, 3, 2])
AX = np.copy(A)
AX[:, 0] = B
AY = np.copy(A)
AY[:, 1] = B
AZ = np.copy(A)
AZ[:, 2] = B
def tinhtoan_dinhthuc(matrix):
    return linalg.det(matrix)
det = tinhtoan_dinhthuc(A)
detX = tinhtoan_dinhthuc(AX)
detY = tinhtoan_dinhthuc(AY)
detZ = tinhtoan_dinhthuc(AZ)
print("\nhệ 3 phương trình:")
print("det =", det, ", detX =", detX, ", detY =", detY, ", detZ =", detZ)
if det != 0:
    x = detX/ det
    y = detY/ det
    z = detZ/ det
    print("nghiệm của hệ là: x =", x, ", y =", y, ", z =", z)
else:
    print("hệ phương trình vô nghiệm hoặc vô số nghiệm")


hệ 2 phương trình:
detA = -14.0 , detA1 = -28.0 , detA2 = 14.000000000000004
nghiệm của hệ là: x1 = 2.0 , x2 = -1.0000000000000002

hệ 3 phương trình:
det = 0.0 , detX = 0.0 , detY = 0.0 , detZ = 0.0
hệ phương trình vô nghiệm hoặc vô số nghiệm


In [3]:
#Thực hành 4
#Tính diện tích tam giác
import sympy as sp
TG = sp.Matrix([[1, 0, 1], [4, 3, 1], [2, 2, 1]])
Stamgiac = 1/2 * TG.det()
print("\ndiện tích tam giác là:", Stamgiac)

#Ứng dụng 1: Tính diện tích đa giác gồm n điểm (xj, yj):
def polygon_area(diem):
    n = len(diem)
    area = 0
    for i in range(n):
        x1, y1 = diem[i]
        x2, y2 = diem[(i+1)%n]
        area += (x1 * y2 - x2 * y1)
    return abs(area) / 2
diem = [(4,10), (9,7), (11,2), (2,2), (2,8)]
print("\ndiện tích đa giác là:", polygon_area(diem))

#Ứng dụng 2: Mở rộng bài toán tính diện tích thành thể tích hình tứ diện:
from sympy import Matrix
M = Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
V = abs(1/6 * M.det())
print("\nthể tích tứ diện là:", V)

#Ứng dụng 3: Kiểm 4 điểm nằm trên một mặt phẳng trong không gian ba chiều
M = Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
if M.det() == 0:
    print("\n4 điểm đồng phẳng")
else:
    print("\n4 điểm không đồng phẳng")

#Ứng dụng 4: Phương trình mặt phẳng
#Hãy viết phương trình mặt phẳng đi qua 3 điểm (-1, 3, 2), (0, 1, 0), (-2, 0, 1)
from sympy import symbols
x, y, z = symbols('x y z')
MP = Matrix([[x, y, z, 1], [-1, 3, 2, 1], [0, 1, 0, 1], [-2, 0, 1, 1]])
kq = MP.det()
print("\nphương trình mặt phẳng là:", kq)



diện tích tam giác là: 1.50000000000000

diện tích đa giác là: 51.5

thể tích tứ diện là: 12.0000000000000

4 điểm không đồng phẳng

phương trình mặt phẳng là: -4*x + 3*y - 5*z - 3


In [4]:
#Thực hành 5
import sympy as sp
a, b, c, d, e, f = sp.symbols('a b c d e f')
diem = [(1, 1), (2, 2), (3, 1), (2, 0), (1, 2)]
equations = []
for x, y in diem:
    eq = a*x**2 + b*x*y + c*y**2 + d*x + e*y + f
    equations.append(eq)
solution = sp.solve([eq.subs(f, 1) for eq in equations], (a, b, c, d, e))
if solution:
    a_val = solution[a]
    b_val = solution[b]
    c_val = solution[c]
    d_val = solution[d]
    e_val = solution[e]
    f_val = 1
    x, y = sp.symbols('x y')
    kq = a_val*x**2 + b_val*x*y + c_val*y**2 + d_val*x + e_val*y + f_val
    print("phương trình ellipse là:")
    sp.pprint(sp.Eq(kq, 0))
else:
    print("không tìm được nghiệm hợp lệ")


phương trình ellipse là:
 2                2              
x    x⋅y   5⋅x   y    2⋅y        
── + ─── - ─── + ── - ─── + 1 = 0
6     6     6    6     3         


#Bài Tập Về Nhà

In [14]:
# Bài 1
import sympy as sp
n = int(input("nhập kích thước ma trận n: "))
A = sp.Matrix([list(map(float, input(f"  hàng {i+1}: ").split())) for i in range(n)])
print("\nma trận A:")
sp.pprint(A)

#a/ ma trận hệ số kép
cofactor = sp.Matrix(
    [ [ (-1)**(i+j) * A.minor_submatrix(i, j).det()  for j in range(n) ]
      for i in range(n) ]
)
print("\nMa trận hệ số kép:")
sp.pprint(cofactor)

#b/ ma trận liên hợp
adjoint = cofactor.T
print("\nMa trận liên hợp:")
sp.pprint(adjoint)


Nhập kích thước ma trận n: 3
  Hàng 1: 1 2 3
  Hàng 2: 4 5 6
  Hàng 3: 7 8 9

Ma trận A:
⎡1.0  2.0  3.0⎤
⎢             ⎥
⎢4.0  5.0  6.0⎥
⎢             ⎥
⎣7.0  8.0  9.0⎦

Ma trận hệ số kép (Cofactor):
⎡-3.0   6.0   -3.0⎤
⎢                 ⎥
⎢6.0   -12.0  6.0 ⎥
⎢                 ⎥
⎣-3.0   6.0   -3.0⎦

Ma trận liên hợp (Adjoint):
⎡-3.0   6.0   -3.0⎤
⎢                 ⎥
⎢6.0   -12.0  6.0 ⎥
⎢                 ⎥
⎣-3.0   6.0   -3.0⎦


In [17]:
#Bài tập 2
import sympy as sp
print(nhập tọa độ 3 điểm (cách nhau bằng dấu cách):")
x1, y1 = map(float, input("điểm 1: ").split())
x2, y2 = map(float, input("điểm 2: ").split())
x3, y3 = map(float, input("điểm 3: ").split())
x, y = sp.symbols('x y')
D, E, Fsym = sp.symbols('D E F')
sols = sp.solve([
    x1**2 + y1**2 + D*x1 + E*y1 + Fsym,
    x2**2 + y2**2 + D*x2 + E*y2 + Fsym,
    x3**2 + y3**2 + D*x3 + E*y3 + Fsym
], (D, E, Fsym), dict=True)
sol = sols[0]

#phương trình đường tròn
eq_circle = x**2 + y**2 + sol[D]*x + sol[E]*y + sol[Fsym]
print("\nphương trình đường tròn:")
sp.pprint(sp.Eq(eq_circle, 0))

#tính tâm và bán kính
h = -sol[D]/2
k = -sol[E]/2
R = sp.sqrt(h**2 + k**2 - sol[Fsym])
print("\ntâm đường tròn O(h, k):")
sp.pprint((h, k))
print("\nbán kính R:")
sp.pprint(R)



Nhập tọa độ 3 điểm (cách nhau bằng dấu cách):
Điểm 1: 0 0
Điểm 2: 0 1
Điểm 3: 1 0

Phương trình đường tròn:
 2            2            
x  - 1.0⋅x + y  - 1.0⋅y = 0

Tâm đường tròn O(h, k):
(0.5, 0.5)

Bán kính R:
0.707106781186548
