#Bài tập thực hành

In [1]:
#Võ Ngọc Duy - 2474802010071
#Thực hành 1.1
import numpy as np
D = np.array([[1, 2], [3, 4]])
E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print("giá trị của E sau khi copyto (E, D): ")
print(E)


giá trị của E sau khi copyto(E, D): 
[[1 2]
 [3 4]]


In [4]:
#Thực hành 1.3
# Import thư viện
from numpy import matlib
G = matlib.identity(5)
print("ma trận đơn vị G:")
print(G)
H = matlib.randn(3, 2)
print("\nma trận ngẫu nhiên H: ")
print(H)
K = matlib.zeros([4, 4])
print("\nma trận toàn số 0 K: ")
print(K)


ma trận đơn vị G:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

ma trận ngẫu nhiên H: 
[[ 0.44055941  0.78216854]
 [-0.91937794  0.87605266]
 [-0.86349622 -0.1073863 ]]

ma trận toàn số 0 K: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#Thực hành 2.2
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.matrix([[1, 0], [0, 1]])
for i in range(len(c)):
    ci = np.matrix([[c[i], 1], [1, 0]])
    M = M.dot(ci)
print("ma trận kết quả: ")
print(M)
pi_approx = M[0, 0] / M[1, 0]
print("\ngiá trị gần đúng của số pi theo biểu diễn liên phân số:", pi_approx)



ma trận kết quả: 
[[165707065  80143857]
 [ 52746197  25510582]]

giá trị gần đúng của số pi theo biểu diễn liên phân số: 3.1415926535897936


In [10]:
#Thực hành 3.2
import numpy as np
#nhập X và Y
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5]
])
Y = np.array([
    [2],
    [4],
    [2],
    [4],
    [6]
])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
#tính A = (X^T * X)^-1 * X^T * Y
A = A1.dot(A2)
print("giá trị các hệ số hồi quy (a0, a1):")
print(A)
a0, a1 = A[0, 0], A[1, 0]
print(f"\nphương trình hồi quy: y = {a0:.1f} + {a1:.1f}x")
f = X.dot(A)
sai_so = f - Y
binh_phuong_sai_so = sai_so ** 2
tong_binh_phuong_sai_so = np.sum(binh_phuong_sai_so)
print("\ntổng bình phương sai số:", tong_binh_phuong_sai_so)



giá trị các hệ số hồi quy (a0, a1):
[[1.2]
 [0.8]]

phương trình hồi quy: y = 1.2 + 0.8x

tổng bình phương sai số: 4.799999999999999


#Bài tập về nhà

In [11]:
#Bài tập 1
import numpy as np
from numpy import linalg
def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append((i+1)*1.0)
    for i in range(len(b)):
        b[i] = b[i] - 1
    x = np.array([o1, b]).T
    y = np.array(a).reshape(-1, 1)
    u = np.linalg.inv(np.dot(x.T, x))
    v = np.dot(x.T, y)
    A = np.dot(u, v)
    return A
dulieu = [10.0, 8, 7.5, 5, 2]
A = bpcuctieu(dulieu)
a0 = A[0][0]
a1 = A[1][0]
print(f"phương trình hồi quy: y = {a0:.1f} + {a1:.1f}x")


phương trình hồi quy: y = 10.3 + -1.9x
