#Bài tập thực hành

In [1]:
#Bài thực hành 1.2
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tich = np.inner(a, b)
print(tich)
print(np.inner(a, b))
print(np.dot(a, b))


32
32
32


In [3]:
#Bài thực hành 3.1
#Tính trạng thái sau 100 tuần
import numpy as np
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
v0 = np.array([[0.95],
               [0.05]])
A_power = np.linalg.matrix_power(A, 100)
v100 = np.dot(A_power, v0)
print("\nvector sau 100 tuần:")
print(v100)

#Trạng thái cân bằng (Markov)
A = np.array([[-0.002, 0.136],
              [1, 1]])
b = np.array([0, 1])
nghiem = np.linalg.solve(A, b)
print("\nnghiệm hệ phương trình (x, y):")
print(nghiem)

#Giải hệ bằng sympy
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])
A = sym.Matrix([[-0.002, 0.136],
                [1, 1]])
b = sym.Matrix([0, 1])
nghiem = sym.solve((A * xy) - b, (x, y))
print("\nnghiệm hệ phương trình là:")
print(sym.pretty(nghiem))



vector sau 100 tuần:
[[0.98550723]
 [0.01449277]]

nghiệm hệ phương trình (x, y):
[0.98550725 0.01449275]

nghiệm hệ phương trình là:
{x: 0.985507246376812, y: 0.0144927536231884}


In [5]:
#Bài thực hành 3.2
#Kiểm tra vector riêng cho ma trận A đã cho
import numpy as np
A = np.array([[1, 5], [6, 2]])
u = np.array([[6], [-5]])
tich = np.dot(A, u)
print("Au = ")
print(tich)
print("\n(-4)u = ")
print(-4 * u)

#Ví dụ tính giá trị riêng của ma trận bằng sympy
import sympy as sym
x, y, Lambda = sym.symbols('x y Lambda')
I = sym.eye(2)
A = sym.Matrix([[2, 3], [3, -6]])
phuongtrinh = sym.Eq(sym.det(Lambda * I - A), 0)
nghiem = sym.solve(phuongtrinh)
print("\ncác trị riêng là:")
print([sym.N(phantu, 4) for phantu in nghiem])
print(sym.pretty(nghiem))


Au = 
[[-19]
 [ 26]]

(-4)u = 
[[-24]
 [ 20]]

các trị riêng là:
[-7.000, 3.000]
[-7, 3]


In [6]:
#Bài tập 3.3
import numpy as np
from numpy import linalg as LA
A = np.array([[2, 3],
              [3, -6]])
print("Ma trận A:")
print(A)
D = np.array([[-7, 0],
              [0, 3]])
print("\nMa trận đường chéo D:")
print(D)
P = np.array([[-1/3, 3],
              [1,    1]])
print("\nMa trận P (vector riêng làm cột):")
print(P)
P_inv = LA.inv(P)
print("\nMa trận nghịch đảo P⁻¹:")
print(P_inv)
print("\nTích A.dot(P):")
print(A.dot(P))
print("\nTích P.dot(D):")
print(P.dot(D))
A_pow_1000 = P @ (D ** 1000) @ P_inv
print("\nMa trận A^1000:")
print(A_pow_1000)
print("\nMa trận D^2:")
print(D ** 2)



Ma trận A:
[[ 2  3]
 [ 3 -6]]

Ma trận đường chéo D:
[[-7  0]
 [ 0  3]]

Ma trận P (vector riêng làm cột):
[[-0.33333333  3.        ]
 [ 1.          1.        ]]

Ma trận nghịch đảo P⁻¹:
[[-0.3  0.9]
 [ 0.3  0.1]]

Tích A.dot(P):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

Tích P.dot(D):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

Ma trận A^1000:
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]

Ma trận D^2:
[[49  0]
 [ 0  9]]


#Bài tập về nhà

In [7]:
#Bài 1
import numpy as np
import math
a = np.array([1, 2, 3])
#a/ mag = np.sqrt(a.dot(a))
mag = np.sqrt(a.dot(a))
print("a:", mag)

#b/ mag = np.sqrt(a @ a)
mag = np.sqrt(a @ a)
print("b:", mag)

#c/ mag = np.sqrt(np.inner(a, a))
mag = np.sqrt(np.inner(a, a))
print("c:", mag)

#d. Dùng lambda và math.sqrt
mag = lambda x: math.sqrt(sum(i**2 for i in x))
print("d:", mag(a))

print("Cả 4 đáp án đều đúng")

a: 3.7416573867739413
b: 3.7416573867739413
c: 3.7416573867739413
d: 3.7416573867739413
Cả 4 đáp án đều đúng


In [9]:
#Bài tập 2
import numpy as np
import math
u = np.array(list(map(float, input("Nhập vector u: ").split())))
v = np.array(list(map(float, input("Nhập vector v: ").split())))

#a/ Tính khoảng cách ||u - v||
distance = np.linalg.norm(u - v)
print("\nkhoảng cách giữa u và v:", distance)

#b/ Tính góc θ giữa u và v
dot_product = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
cos_theta = dot_product / (norm_u * norm_v)
cos_theta = np.clip(cos_theta, -1, 1)
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)
print("góc giữa u và v (radian):", theta_rad)
print("góc giữa u và v (độ):", theta_deg)

#c/ Phép chiếu trực giao của u lên v
proj_scalar = np.dot(u, v) / np.dot(v, v)
projection = proj_scalar * v
print("\nphép chiếu trực giao của u lên v:", projection)


Nhập vector u: 1 2 3
Nhập vector v: 4 5 6

khoảng cách giữa u và v: 5.196152422706632
góc giữa u và v (radian): 0.2257261285527342
góc giữa u và v (độ): 12.933154491899135

phép chiếu trực giao của u lên v: [1.66233766 2.07792208 2.49350649]
