#Bài tập thực hành

In [1]:
#Thực hành 1
#Bài tập 1
import numpy as np
u = np.array([2, -1.5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6.2, 0, 3])

u = np.array([2, -1.5, 0])
v = np.array([4, 3, 1])
w = np.array([-6.2, 0, 3])
#a
x_a = 2*u - (v + 3*w)
print("Kết quả câu a (x):", x_a)
#b
x_b = 0.5*(2*u - v - 3*w)
print("Kết quả câu b (x):", x_b)


Kết quả câu a (x): [ 18.6  -6.  -10. ]
Kết quả câu b (x): [ 9.3 -3.  -5. ]


In [2]:
#Bài tập 2
import numpy as np
from numpy import linalg
A = np.array([[0, -1, 3],
              [1,  1, 1],
              [4,  2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print("Giá trị a, b, c lần lượt là:")
print("a =", X[0])
print("b =", X[1])
print("c =", X[2])


Giá trị a, b, c lần lượt là:
a = 1.0
b = -2.0
c = -1.0


In [3]:
#Bài tập 3
import numpy as np
from numpy import linalg as LA
A = np.matrix([[1, 0], [0, 0]])
B = np.matrix([[0, 0], [0, 1]])
#Phương pháp 1
try:
    print("Nghịch đảo A:", LA.inv(A))
except np.linalg.LinAlgError:
    print("A không khả nghịch (Singular Matrix)")
try:
    print("Nghịch đảo B:", LA.inv(B))
except np.linalg.LinAlgError:
    print("B không khả nghịch (Singular Matrix)")

try:
    print("Nghịch đảo A + B:", LA.inv(A + B))
except np.linalg.LinAlgError:
    print("A + B không khả nghịch (Singular Matrix)")
#Phương pháp 2
print("Định thức A:", LA.det(A))
print("Định thức B:", LA.det(B))
print("Định thức A + B:", LA.det(A + B))


A không khả nghịch (Singular Matrix)
B không khả nghịch (Singular Matrix)
Nghịch đảo A + B: [[1. 0.]
 [0. 1.]]
Định thức A: 0.0
Định thức B: 0.0
Định thức A + B: 1.0


In [4]:
#Bài tập 4
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y], [y, x]])
print("A.T:")
print(A.T)
print("A.T == A:", A.T.equals(A))
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1], [y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2], [y2, x2]])
print("(A1 + A2).T:")
print((A1 + A2).T)
print("Tổng có đối xứng không:", ((A1 + A2).T).equals(A1 + A2))
c = sp.symbols('c')
print("c*A:")
print(c*A)
print("c*A có đối xứng không:", ((c*A).T).equals(c*A))


A.T:
Matrix([[x, y], [y, x]])
A.T == A: True
(A1 + A2).T:
Matrix([[x1 + x2, y1 + y2], [y1 + y2, x1 + x2]])
Tổng có đối xứng không: True
c*A:
Matrix([[c*x, c*y], [c*y, c*x]])
c*A có đối xứng không: True


In [6]:
#Bài tập 5
import numpy as np
from numpy.linalg import solve, LinAlgError
v1 = np.array([1, 2, 3])
v2 = np.array([0, 1, 2])
v3 = np.array([-1, 0, 1])
A = np.column_stack([v1, v2, v3])
#câu a: w = (1, 1, 1)
w1 = np.array([1, 1, 1])
try:
    c = solve(A, w1)
    print("Vector (1,1,1) là tổ hợp tuyến tính của v1, v2, v3")
    print("Hệ số tổ hợp:", c)
except LinAlgError:
    print("Vector (1,1,1) không là tổ hợp tuyến tính của v1, v2, v3")
#câu b: w = (1, -2, 2)
w2 = np.array([1, -2, 2])
try:
    c = solve(A, w2)
    print("Vector (1,-2,2) là tổ hợp tuyến tính của v1, v2, v3")
    print("Hệ số tổ hợp:", c)
except LinAlgError:
    print("Vector (1,-2,2) không là tổ hợp tuyến tính của v1, v2, v3")


Vector (1,1,1) là tổ hợp tuyến tính của v1, v2, v3
Hệ số tổ hợp: [ 5.00000000e-01 -1.66533454e-16 -5.00000000e-01]
Vector (1,-2,2) là tổ hợp tuyến tính của v1, v2, v3
Hệ số tổ hợp: [ 3.15251974e+16 -6.30503948e+16  3.15251974e+16]


In [7]:
#Bài tập 6
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
result = sp.solve([c1 + 2*c3, 2*c1 + c2, 3*c1 + 2*c2 + c3], [c1, c2, c3])
print(result)


{c1: 0, c2: 0, c3: 0}


In [9]:
#Bài tập 7
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
giaiphapchung = sp.solve([c1 + c2 - u1, c1 - c2 - u2], [c1, c2])
print("Nghiệm tổng quát:")
print(giaiphapchung)
u1_val = 0
u2_val = 0
giaiphapcuthe = sp.solve([c1 + c2 - u1_val, c1 - c2 - u2_val], [c1, c2])
print("\nNghiệm khi u = (0, 0):")
print(giaiphapcuthe)


Nghiệm tổng quát:
{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

Nghiệm khi u = (0, 0):
{c1: 0, c2: 0}


In [10]:
#Thực hành 2.2
import numpy as np

# Tọa độ chữ F gốc
P = np.array([[0,0,3,3,1,1,2,2,1,1],
              [0,5,5,4,4,3,3,2,2,0]])
#a
vecdelta_a = np.array([4, 2])
P_caua = (P + vecdelta_a[:, None]).T
print("a")
print(P_caua)

#b
vecdelta_b = np.array([4, -2])
matran_biendoi_b = np.array([[1.0, 0.0],
                             [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi_b + vecdelta_b).T
print("\nnb")
print(P_caub)

#c
vecdelta_c = np.array([6, 1])
matran_biendoi_c = np.array([[-1, 0],
                             [0, 1]])
P_cauc = (P.T @ matran_biendoi_c + vecdelta_c).T
print("\nc:")
print(P_cauc)

# d
vecdelta_d = np.array([0, 1])
matran_biendoi_d = np.array([[1, 1],
                             [1, 1]])
P_caud = (P.T @ matran_biendoi_d + vecdelta_d).T
print("\nd:")
print(P_caud)

a
[[4 2]
 [4 7]
 [7 7]
 [7 6]
 [5 6]
 [5 5]
 [6 5]
 [6 4]
 [5 4]
 [5 2]]

nb
[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]

c:
[[6 6 3 3 5 5 4 4 5 5]
 [1 6 6 5 5 4 4 3 3 1]]

d:
[[0 5 8 7 5 4 5 4 3 1]
 [1 6 9 8 6 5 6 5 4 2]]


In [12]:
#Thực hành 3.1
# Thực hành 3.1
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
q = sp.symbols('q')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify((x1, x2, x3), bieuthuc1, 'numpy')
X = (a, b, c)
Y = (d, e, f)
X_plus_Y = (a + d, b + e, c + f)
print("Kiểm tra tính cộng với f1:")
print("f1(X) + f1(Y) =", f1(*X) + f1(*Y))
print("f1(X + Y)     =", f1(*X_plus_Y))
print("=>", f1(*X) + f1(*Y) == f1(*X_plus_Y))
lhs1 = q * f1(*X) + f1(*Y)
rhs1 = f1(q * a + d, q * b + e, q * c + f)
print("\nKiểm tra tính nhân vô hướng với f1:")
print("q*f1(X) + f1(Y) =", lhs1)
print("f1(q*X + Y)     =", rhs1)
print("=>", sp.expand(lhs1) == sp.expand(rhs1))
bieuthuc2 = 2 * x1 + 3 * x3
f2 = lambdify((x1, x2, x3), bieuthuc2, 'numpy')
lhs2 = q * f2(*X) + f2(*Y)
rhs2 = f2(q * a + d, q * b + e, q * c + f)
print("\nKiểm tra với f2:")
print("q*f2(X) + f2(Y) =", lhs2)
print("f2(q*X + Y)     =", rhs2)
print("=>", sp.expand(lhs2) == sp.expand(rhs2))

Kiểm tra tính cộng với f1:
f1(X) + f1(Y) = a - b + c + d - e + f
f1(X + Y)     = a - b + c + d - e + f
=> True

Kiểm tra tính nhân vô hướng với f1:
q*f1(X) + f1(Y) = d - e + f + q*(a - b + c)
f1(q*X + Y)     = a*q - b*q + c*q + d - e + f
=> True

Kiểm tra với f2:
q*f2(X) + f2(Y) = 2*d + 3*f + q*(2*a + 3*c)
f2(q*X + Y)     = 2*a*q + 3*c*q + 2*d + 3*f
=> True


In [13]:
#Thực hành 3.2
import numpy as np
u1 = np.array([1, 2])
u2 = np.array([3, 5])
target = np.array([4, 5])
A = np.column_stack((u1, u2))
b = target
alpha_beta = np.linalg.solve(A, b)
alpha, beta = alpha_beta
print(f"alpha = {alpha}, beta = {beta}")
f_u1 = np.array([1, 1, 2])
f_u2 = np.array([4, 2, 1])
f_target = alpha * f_u1 + beta * f_u2
print(f"f(4,5) = {f_target}")

alpha = -5.0, beta = 3.0
f(4,5) = [ 7.  1. -7.]


In [17]:
#Thực hành 3.3
import sympy as sp
x, y = sp.symbols('x y')
a = -5*x + 3*y
b = 2*x - y
fu1 = sp.Matrix([1, 1, 2])
fu2 = sp.Matrix([4, 2, 1])
f_xy = a * fu1 + b * fu2
print(f"\nf(x, y) = ({f_xy[0]}, {f_xy[1]}, {f_xy[2]})")


f(x, y) = (3*x - y, -x + y, -8*x + 5*y)


In [19]:
#Thực hành 3.4
import sympy as sp
x1, x2, x3 = sp.symbols('x1 x2 x3')
eq1 = x1 + x2 - x3
eq2 = 2*x1 + 3*x2 - 3*x3
eq3 = 3*x1 + 5*x2 - x3
solution = sp.solve([eq1, eq2, eq3], [x1, x2, x3], dict=True)
print("Nghiệm tổng quát của hệ phương trình:")
sp.pprint(solution)
t = sp.symbols('t')
x3_val = t
x2_val = -t
x1_val = 2*t
ker_vector = sp.Matrix([x1_val, x2_val, x3_val])
print("\nMột cơ sở của Ker(f):")
sp.pprint(ker_vector)
print("\nKhông gian nhân của f là: Ker(f) = span({})".format(ker_vector))

Nghiệm tổng quát của hệ phương trình:
[{x₁: 0, x₂: 0, x₃: 0}]

Một cơ sở của Ker(f):
⎡2⋅t⎤
⎢   ⎥
⎢-t ⎥
⎢   ⎥
⎣ t ⎦

Không gian nhân của f là: Ker(f) = span(Matrix([[2*t], [-t], [t]]))


In [20]:
#Thực hành 3.5
import sympy as sp
x1, x2, x3 = sp.symbols('x1 x2 x3')
def f(x1, x2, x3):
    return sp.Matrix([
        x1 + x2 - x3,
        2*x1 + 3*x2 - 3*x3,
        3*x1 + 5*x2 - x3
    ])
basis = [
    (1, 0, 0),
    (0, 1, 0),
    (0, 0, 1)
]
images = [f(*vec) for vec in basis]
print("Các vector f(u1), f(u2), f(u3):")
for i, v in enumerate(images, 1):
    print(f"f(u{i}) = ")
    sp.pprint(v)
    print()
M = sp.Matrix.hstack(*images)
image_basis = M.columnspace()
print("Cơ sở của ảnh ánh xạ Imf là:")
for v in image_basis:
    sp.pprint(v)

Các vector f(u1), f(u2), f(u3):
f(u1) = 
⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

f(u2) = 
⎡1⎤
⎢ ⎥
⎢3⎥
⎢ ⎥
⎣5⎦

f(u3) = 
⎡-1⎤
⎢  ⎥
⎢-3⎥
⎢  ⎥
⎣-1⎦

Cơ sở của ảnh ánh xạ Imf là:
⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦
⎡1⎤
⎢ ⎥
⎢3⎥
⎢ ⎥
⎣5⎦
⎡-1⎤
⎢  ⎥
⎢-3⎥
⎢  ⎥
⎣-1⎦


In [21]:
#Bài tập 3.6
import sympy as sp
x, y = sp.symbols('x y')
def f(x, y):
    return sp.Matrix([x - y, x])
u1 = sp.Matrix([-1, 1])
u2 = sp.Matrix([1, 0])
v1 = sp.Matrix([1, 2])
v2 = sp.Matrix([1, 3])
F = sp.Matrix.hstack(v1, v2)
fu1 = f(*u1)
fu2 = f(*u2)
a1, b1 = sp.symbols('a1 b1')
a2, b2 = sp.symbols('a2 b2')
sol1 = sp.linsolve([(a1 * v1 + b1 * v2)[i] - fu1[i] for i in range(2)], (a1, b1))
sol2 = sp.linsolve([(a2 * v1 + b2 * v2)[i] - fu2[i] for i in range(2)], (a2, b2))
[a1_val, b1_val] = list(sol1)[0]
[a2_val, b2_val] = list(sol2)[0]
A = sp.Matrix([[a1_val, a2_val], [b1_val, b2_val]])
print("Ma trận ánh xạ tuyến tính A = [f]^F_B là:")
sp.pprint(A)

Ma trận ánh xạ tuyến tính A = [f]^F_B là:
⎡-5  2 ⎤
⎢      ⎥
⎣3   -1⎦


In [22]:
#Thực hành 4
import sympy as sp
x, y, xp, yp = sp.symbols('x y x_p y_p')
cos_theta = 1/sp.sqrt(2)
sin_theta = 1/sp.sqrt(2)
x_sub = cos_theta * xp - sin_theta * yp
y_sub = sin_theta * xp + cos_theta * yp
f = 5*x**2 - 6*x*y + 5*y**2 + 14*sp.sqrt(2)*x - 2*sp.sqrt(2)*y + 18
f_rotated = f.subs({x: x_sub, y: y_sub})
f_rotated = sp.simplify(f_rotated)
print("Phương trình sau khi quay hệ trục:")
sp.pprint(f_rotated)

Phương trình sau khi quay hệ trục:
    2               2             
2⋅xₚ  + 12⋅xₚ + 8⋅yₚ  - 16⋅yₚ + 18


#Bài tập về nhà

In [23]:
#Bài tập 1
import sympy as sp
x, y, z = sp.symbols('x y z')
a, b, c = sp.symbols('a b c')
t = sp.Symbol('t')
def g(v):
    x, y, z = v
    return sp.Matrix([x + y, z + 2, 0])
u = sp.Matrix([x, y, z])
v = sp.Matrix([a, b, c])
left = g(u + v)
right = g(u) + g(v)
print("Kiểm tra g(u + v) == g(u) + g(v):")
print("g(u + v) =", left)
print("g(u) + g(v) =", right)
print("Kết quả:", sp.simplify(left - right) == sp.Matrix([0,0,0]))
left2 = g(t * u)
right2 = t * g(u)
print("\nKiểm tra g(t*u) == t*g(u):")
print("g(t*u) =", left2)
print("t * g(u) =", right2)
print("Kết quả:", sp.simplify(left2 - right2) == sp.Matrix([0,0,0]))
zero = sp.Matrix([0, 0, 0])
print("\nKiểm tra g(0) == 0:")
print("g(0) =", g(zero))

Kiểm tra g(u + v) == g(u) + g(v):
g(u + v) = Matrix([[a + b + x + y], [c + z + 2], [0]])
g(u) + g(v) = Matrix([[a + b + x + y], [c + z + 4], [0]])
Kết quả: False

Kiểm tra g(t*u) == t*g(u):
g(t*u) = Matrix([[t*x + t*y], [t*z + 2], [0]])
t * g(u) = Matrix([[t*(x + y)], [t*(z + 2)], [0]])
Kết quả: False

Kiểm tra g(0) == 0:
g(0) = Matrix([[0], [2], [0]])


In [24]:
#Bài tập 2
import numpy as np
A = np.array([[0, 1],
              [1, -1]])
F = np.array([[1, 2], [2, 3], [0, 1]])
for point in F:
    transformed = A @ point
    print(f"g({point}) = {transformed}")


g([1 2]) = [ 2 -1]
g([2 3]) = [ 3 -1]
g([0 1]) = [ 1 -1]


In [ ]:
#Bài tập 3
import sympy as sp
v1, v2, w1, w2, c = sp.symbols('v1 v2 w1 w2 c')
v = sp.Matrix([v1, v2])
w = sp.Matrix([w1, w2])
def T(vec):
    x, y = vec
    return sp.Matrix([x - y, x + 2*y])
left_add = T(v + w)
right_add = T(v) + T(w)
left_scalar = T(c * v)
right_scalar = c * T(v)
print("Tuyến tính cộng đúng:", sp.simplify(left_add - right_add) == sp.Matrix([0, 0]))
print("Tuyến tính nhân vô hướng đúng:", sp.simplify(left_scalar - right_scalar) == sp.Matrix([0, 0]))

In [25]:
#Bài tập 4
import sympy as sp
A = sp.Matrix([[13, -5],
               [-5, 13]])
eigen_data = A.diagonalize(normalize=True)
P = eigen_data[0]
D = eigen_data[1]
v1 = P[:, 0]
cos_theta = v1[0]
sin_theta = v1[1]
theta = sp.atan2(sin_theta, cos_theta)*180/sp.pi
print("Ma trận A:")
sp.pprint(A)
print("\nMa trận trực giao P (xoay hệ trục):")
sp.pprint(P)
print("\nMa trận đường chéo D (dạng chính tắc):")
sp.pprint(D)
print("\nGóc xoay θ để khử xy (độ):")
sp.pprint(sp.simplify(theta))

Ma trận A:
⎡13  -5⎤
⎢      ⎥
⎣-5  13⎦

Ma trận trực giao P (xoay hệ trục):
⎡√2  -√2 ⎤
⎢──  ────⎥
⎢2    2  ⎥
⎢        ⎥
⎢√2   √2 ⎥
⎢──   ── ⎥
⎣2    2  ⎦

Ma trận đường chéo D (dạng chính tắc):
⎡8  0 ⎤
⎢     ⎥
⎣0  18⎦

Góc xoay θ để khử xy (độ):
45
