#Đề Thi Thử Thực Hành Đại Số Tuyến Tính

In [13]:
#Câu 1
import numpy as np
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])
# Câu a
tong_AB = A + B
bieuthuc = 3 * A - 2 * B
print("a/ A + B =", tong_AB)
print("\n3A - 2B =", bieuthuc)

# Câu b
tich_vo_huong = np.dot(A, B)
do_dai_A = np.linalg.norm(A)
do_dai_B = np.linalg.norm(B)
cos_theta = tich_vo_huong / (do_dai_A * do_dai_B)
goc = np.degrees(np.arccos(cos_theta))
print("b/ Tích vô hướng A · B =", tich_vo_huong)
print("\nGóc giữa A và B =", round(goc, 3), "độ")

# Câu c
CtC = C.T @ C
print("\nc/ tích ma trận C^T · C")
print(CtC)

a/ A + B = [3 3 1 5]

3A - 2B = [  4 -11  13 -10]
b/ Tích vô hướng A · B = -8

Góc giữa A và B = 108.376 độ

c/ tích ma trận C^T · C
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [12]:
#Câu 2
import numpy as np

# Khai báo ma trận M và N
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [0, 1, 1, 0]])

N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])
# Câu a
MN = M @ N
print("\na/ tích ma trận M × N ")
print(MN)

# Câu b
if M.shape[0] == M.shape[1]:
    det_M = np.linalg.det(M)
    print("\nb/ định thức của ma trận M =", round(det_M, 3))
else:
    print("\nb/ không tính được định thức vì M không phải là ma trận vuông")

# Câu c
rank_N = np.linalg.matrix_rank(N)
print("\nc/ hạng của ma trận N =", rank_N)


a/ tích ma trận M × N 
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b/ định thức của ma trận M = 0.0

c/ hạng của ma trận N = 2


In [14]:
#Câu 3
import numpy as np
P = np.array([[2, 1, 0, 1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])
# Câu a
try:
    P_inv = np.linalg.inv(P)
    print("\n a/ Ma trận nghịch đảo của P là:")
    print(P_inv)
except np.linalg.LinAlgError:
    print("Ma trận P không khả nghịch vì định thức bằng 0")

# Câu b
if 'P_inv' in locals():
    x = P_inv @ b
    print("\nb/Nghiệm của hệ phương trình là:")
    print("x =", round(x[0], 3))
    print("y =", round(x[1], 3))
    print("z =", round(x[2], 3))
    print("w =", round(x[3], 3))
else:
    print("Không thể giải vì không có nghịch đảo của P")

# Câu c
if 'x' in locals():
    check = P @ x
    print("\nc/ Tích P · x =", check)
    print("Vector hằng số b =", b)
    print("Hai vector có khớp nhau không? =>", np.allclose(check, b))
else:
    print("Không thể kiểm tra vì chưa có nghiệm.")


 a/ Ma trận nghịch đảo của P là:
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b/Nghiệm của hệ phương trình là:
x = 0.465
y = 2.105
z = 1.651
w = 0.965

c/ Tích P · x = [4. 7. 9. 5.]
Vector hằng số b = [4 7 9 5]
Hai vector có khớp nhau không? => True


In [ ]:
# Câu 4
import numpy as np
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(Q)

# Câu a
for i, val in enumerate(eigenvalues):
    val_real = np.round(val.real, 4)
    val_imag = np.round(val.imag, 4)
    if np.isclose(val.imag, 0):
        print(f"a/ Giá trị riêng Q{i+1} = {val_real}")
    else:
        print(f"a/ Giá trị riêng Q{i+1} = {val_real} + {val_imag}j")

# Câu b
print("\nb/ Vector riêng tương ứng với các giá trị riêng")
for i in range(len(eigenvalues)):
    eig_val = eigenvalues[i]
    print(f"Vector riêng ứng với Q{i+1} = {np.round(eig_val, 4)}:")
    print(np.round(eigenvectors[:, i], 4))

# Câu c
print("\nc/ Chuẩn hóa tất cả các vector riêng")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    v_norm = v / np.linalg.norm(v)
    print(f"Vector riêng {i+1}:")
    print(np.round(v_norm, 4))

a/ Giá trị riêng Q1 = 3.4534
a/ Giá trị riêng Q2 = 2.7733 + 1.4677j
a/ Giá trị riêng Q3 = 2.7733 + -1.4677j

b/ Vector riêng tương ứng với các giá trị riêng
Vector riêng ứng với Q1 = (3.4534+0j):
[0.8333+0.j 0.4555+0.j 0.3134+0.j]
Vector riêng ứng với Q2 = (2.7733+1.4677j):
[-0.2621-0.3135j -0.7817+0.j     -0.2196+0.4169j]
Vector riêng ứng với Q3 = (2.7733-1.4677j):
[-0.2621+0.3135j -0.7817-0.j     -0.2196-0.4169j]

c/ Chuẩn hóa tất cả các vector riêng
Vector riêng 1:
[0.8333+0.j 0.4555+0.j 0.3134+0.j]
Vector riêng 2:
[-0.2621-0.3135j -0.7817+0.j     -0.2196+0.4169j]
Vector riêng 3:
[-0.2621+0.3135j -0.7817+0.j     -0.2196-0.4169j]


In [22]:
#Câu 5
import numpy as n
R = np.array([[1, -2, 3],
              [2,  0, 1],
              [-1, 1, 4]])
b = np.array([10, 8, 7])

# Câu a
x1 = np.linalg.solve(R, b)
print("\na/ Nghiệm x của hệ phương trình Rx = b là:")
print(x1)

# Câu b
if np.linalg.det(R) != 0:
    R_inv = np.linalg.inv(R)
    x2 = R_inv @ b
    print("\nb) Ma trận R khả nghịch")
    print("Nghiệm x (dùng ma trận nghịch đảo):")
    print(x2)
    print("Hai nghiệm giống nhau:", np.allclose(x1, x2))
else:
    print("\nb/ Ma trận R không khả nghịch")

# Câu c
fro_norm = np.linalg.norm(R, ord='fro')
print("\nc/ Chuẩn Frobenius của ma trận R là:", round(fro_norm, 4))


a/ Nghiệm x của hệ phương trình Rx = b là:
[2.7826087  0.04347826 2.43478261]

b) Ma trận R khả nghịch
Nghiệm x (dùng ma trận nghịch đảo):
[2.7826087  0.04347826 2.43478261]
Hai nghiệm giống nhau: True

c/ Chuẩn Frobenius của ma trận R là: 6.0828
